import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { CssBaseline, ThemeProvider } from "@mui/material";

import { theme } from "@theme/theme";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
